kangaroo:
  singular:
    - le kangourou
    - il canguro
  plural:
    - les kangourou
    - i canguri
shark:
  singular:
    - le requin
    - lo squalo
  plural:
    - les requins
    - gli squali
giraffe:
  singular:
    - la girafe
    - la giraffa
  plural:
    - les girafes
    - le giraffe
squirrel:
  singular:
    - l'écureuil 
    - lo scoiattolo
  plural:
    - les écureuils
    - gli scoiattoli
horse:
  singular:
    - le cheval 
    - il cavallo
  plural:
    - les chevaux
    - i cavalli
dove:
  singular:
    - la colombe 
    - la colomba
  plural:
    - les colombes
    - le colombe

    
