kangaroo:
  singular:
    - le kangourou
    - il canguro
  plural:
    - les kangourou
    - i canguri
shark:
  singular:
    - le requin
    - lo squalo
  plural:
    - les requins
    - gli squali
giraffe:
  singular:
    - la girafe
    - la giraffa
  plural:
    - les girafes
    - le giraffe

    
