kangaroo:
  singular:
    - le kangourou
    - il canguro
  plural:
    - les kangourou
    - i canguri
shark:
  singular:
    - le requin
    - lo squalo
  plural:
    - les requins
    - gli squali
giraffe:
  singular:
    - la girafe
    - la giraffa
  plural:
    - les girafes
    - le giraffe
squirrel:
  singular:
    - l'écureuil 
    - lo scoiattolo
  plural:
    - les écureuils
    - gli scoiattoli
horse:
  singular:
    - le cheval 
    - il cavallo
  plural:
    - les chevaux
    - i cavalli
dove:
  singular:
    - la colombe 
    - la colomba
  plural:
    - les colombes
    - le colombe
octopus:
  singular:
    - la pieuvre 
    - il polpo
  plural:
    - les pieuvres
    - i polpi
raven:
  singular:
    - le corbeau 
    - il corvo
  plural:
    - les corbeaux
    - i corvi
hedgehog:
  singular:
    - le hérisson 
    - il riccio
  plural:
    - les hérissons
    - i ricci
puppy:
  singular:
    - le chiot 
    - il cucciolo
  plural:
    - les chiots
    - i cuccioli
kitten:
  singular:
    - le chaton 
    - il gattino
  plural:
    - les chatons
    - i gattini
    
