bathroom:
  bathtub:
    - la bagnoire
    - la vasca
  shower:
    - la douche
    - la doccia
  sink:
    - la lavabo
    - il lavandino
  toilet:
    - le toilettes
    - il water
kitchen:
  oven:
    - le four
    - il forno
  microwave:
    - le four à micro-ondes
    - il microonde
  fork:
    - la forchette
    - la forchetta
  spoon:
    - la cuilliere
    - cucchaio
  knife:
    - le couteau
    - il cotello
  plate:
    - la assiette
    - piatto
  glass:
    - le verre
    - bicchiere
  cup:
    - la tasse
    - la tazza
  refrigerator:
    - le réfrigérateur
    - il frigorifero
  sink: 
    - l'évier
    - il lavandino
  
